Resources:
  GithubOidc:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList: 
        - sts.amazonaws.com
      ThumbprintList:
        - a031c46782e6e6c662c2c87c76da9aa62ccabd8e

  GitHubMattCantyDNSActionsWriteRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: GitHubMattCantyDNSActionsWrite
      ManagedPolicyArns: [arn:aws:iam::aws:policy/ReadOnlyAccess]
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !Ref GithubOidc
            Condition:
              StringLike:
                token.actions.githubusercontent.com:sub: repo:mattcanty/dns:*

Outputs:
  Role:
    Value: !GetAtt GitHubMattCantyDNSActionsWriteRole.Arn   
