Resources:
  GithubOidc:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList: 
        - sts.amazonaws.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1

  GitHubMattCantyDNSActionsWriteRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: GitHubMattCantyDNSActionsWrite
      ManagedPolicyArns: [arn:aws:iam::aws:policy/ReadOnlyAccess]
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !Ref GithubOidc
            Condition:
              StringLike:
                token.actions.githubusercontent.com:sub: repo:mattcanty/dns:*
      Policies:
        - PolicyName: GitHubMattCantyDNSActionsManageRoute53
          PolicyDocument:
            Version: "2012-10-17"
            Statement: 
              - Effect: Allow
                Action:
                  - route53:CreateHostedZone
                  - route53:GetHostedZone
                  - route53:ListHostedZones
                  - route53:ChangeResourceRecordSets
                  - route53:ListResourceRecordSets
                  - route53:UpdateHostedZoneComment
                Resource: "*"

Outputs:
  Role:
    Value: !GetAtt GitHubMattCantyDNSActionsWriteRole.Arn   
